image:
  repository: ghcr.io/kanboard/kanboard
  tag: v1.2.49@sha256:84703c948f1b403267c6cf426c1b66da320dd67c4aa280d36b2f21f8b7c2ab9a
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10015
        targetPort: 80
persistence:
  data:
    enabled: true
    mountPath: "/var/www/app/data"
  ssl:
    enabled: true
    mountPath: "/etc/nginx/ssl"
cnpg:
  main:
    enabled: true
    user: kanboard
    database: kanboard

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            MAIL_CONFIGURATION: false
            LOG_DRIVER: stdout
            DB_DRIVER: "postgres"
            DB_NAME: "{{ .Values.cnpg.main.database }}"
            DB_USERNAME: "{{ .Values.cnpg.main.user }}"
            DB_PORT: "5432"
            DB_PASSWORD:
              secretKeyRef:
                name: cnpg-main-user
                key: password
            DB_HOSTNAME:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
