image:
  repository: docker.io/syncthing/syncthing
  pullPolicy: IfNotPresent
  tag: 2.0.5@sha256:dd8298202efe3897107c718331b37517ca8a1623fbd37bba74aec426941013c0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: /rest/noauth/health
            readiness:
              path: /rest/noauth/health
            startup:
              path: /rest/noauth/health
service:
  main:
    ports:
      main:
        port: 8384
        targetPort: 8384
  listeners:
    enabled: true
    ports:
      tcp:
        enabled: true
        port: 22000
        targetPort: 22000
  listeners-udp:
    enabled: true
    ports:
      udp:
        enabled: true
        port: 22000
        targetPort: 22000
        protocol: udp
  discovery:
    enabled: true
    ports:
      discovery:
        enabled: true
        port: 21027
        targetPort: 21027
        protocol: udp
persistence:
  config:
    enabled: true
    mountPath: "/var/syncthing"
