image:
  repository: ghcr.io/linuxserver/jackett
  pullPolicy: IfNotPresent
  tag: 0.24.222@sha256:efd835e81e78b48f8c129bff486e3d63a069a905e76ae8698935bb84a4e6103e

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp

redis:
  enabled: false
mariadb:
  enabled: false
mongodb:
  enabled: false
