image:
  repository: ghcr.io/linuxserver/jackett
  pullPolicy: IfNotPresent
  tag: 0.24.141@sha256:a1a1b1927f2ed4d8d6e91f0931d6b46dd0ad222ecb92cafe26f049fa81191151

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp

redis:
  enabled: false
mariadb:
  enabled: false
mongodb:
  enabled: false
