image:
  repository: ghcr.io/linuxserver/jackett
  pullPolicy: IfNotPresent
  tag: 0.24.234@sha256:52c9ed49c4e5783966663e7069f8b5ae55fa1aec134ea2db0f6817a954703203

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp

redis:
  enabled: false
mariadb:
  enabled: false
mongodb:
  enabled: false
