image:
  repository: ghcr.io/linuxserver/jackett
  pullPolicy: IfNotPresent
  tag: 0.24.179@sha256:c26bf5041b4ffb861509f09fc3df9f33591e06ed75413f95b54a06009ea3ee55

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp

redis:
  enabled: false
mariadb:
  enabled: false
mongodb:
  enabled: false
