image:
  repository: ghcr.io/linuxserver/jackett
  pullPolicy: IfNotPresent
  tag: 0.24.170@sha256:798be8612475cf6b6e3d814c4779554574172bb64a596d96a6040d40f92328ed

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp

redis:
  enabled: false
mariadb:
  enabled: false
mongodb:
  enabled: false
