image:
  repository: docker.io/shlinkio/shlink
  pullPolicy: IfNotPresent
  tag: 4.6.0@sha256:e607cd6f8c7f6bfd4cc734c812538d4123602c455a439c43dd02b35af885948f
service:
  main:
    ports:
      main:
        port: 10153
cnpg:
  main:
    enabled: true
    user: shlink
    database: shlink
redis:
  enabled: true
  redisUsername: "default"

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/rest/health"
            readiness:
              path: "/rest/health"
            startup:
              path: "/rest/health"
          env:
            DEFAULT_DOMAIN: ""
            GEOLITE_LICENSE_KEY: ""
            ANONYMIZE_REMOTE_ADDR: true
            ENABLE_PERIODIC_VISIT_LOCATE: true
            IS_HTTPS_ENABLED: true
            PORT: "{{ .Values.service.main.ports.main.port }}"
            DB_DRIVER: "postgres"
            DB_USER: "{{ .Values.cnpg.main.user }}"
            DB_NAME: "{{ .Values.cnpg.main.database }}"
            DB_PASSWORD:
              secretKeyRef:
                name: cnpg-main-user
                key: password
            DB_HOST:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
            REDIS_SERVERS:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: url
