image:
  repository: ghcr.io/linuxserver/grav
  pullPolicy: IfNotPresent
  tag: 1.7.49@sha256:3e528ac3597202cb4dda3d0aac3d50feee82c4002b368a1b3650563324cbbbde
service:
  main:
    ports:
      main:
        port: 10012
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
