image:
  repository: ghcr.io/lissy93/dashy
  tag: latest@sha256:4ac1642c78e6fdb4628d0ced9b70ea2b96d16189bd5d1d01d75a1dff6030519f
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10310
        protocol: http
        targetPort: 8080
resources:
  limits:
    cpu: 2000m
    memory: 3000Mi
  requests:
    cpu: 200m
    memory: 500Mi
dashy:
  # Enable config directory mount from host path
  enabled: false
  configDirectoryHostPath: ""
  configDirectoryHostReadOnly: true
# Leave empty if you plan to use config directory from host path
dashyConfig: {}
# pageInfo:
#   title: Home Lab

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NODE_ENV: production
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                exec:
                  command:
                    - node
                    - /app/services/healthcheck
            readiness:
              enabled: true
              custom: true
              spec:
                exec:
                  command:
                    - node
                    - /app/services/healthcheck
            startup:
              enabled: true
              custom: true
              spec:
                exec:
                  command:
                    - node
                    - /app/services/healthcheck
persistence:
  icons:
    enabled: true
    mountPath: /app/public/item-icons
