image:
  repository: ghcr.io/emberstack/kubernetes-reflector
  pullPolicy: IfNotPresent
  tag: 9.1.32@sha256:3209a9d3036eb7a597d9489be4bd2f4e34f4d343521631f0c2fac2e61e140d60
operator:
  register: true

rbac:
  main:
    enabled: true
    primary: true
    clusterWide: true
    rules:
      - apiGroups:
          - ""
        resources:
          - "configmaps"
          - "secrets"
        verbs:
          - "get"
          - "list"
          - "watch"
          - "create"
          - "update"
          - "patch"
          - "delete"
      - apiGroups:
          - ""
        resources:
          - "namespaces"
        verbs:
          - "watch"
          - "list"
serviceAccount:
  main:
    enabled: true
    primary: true
kubernetesReflector:
  logLevel: Information
workload:
  main:
    podSpec:
      automountServiceAccountToken: true
      containers:
        main:
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          env:
            ES_Serilog__MinimumLevel__Default: "{{ .Values.kubernetesReflector.logLevel }}"
            ES_Reflector__Watcher__Timeout: ""
            ES_Reflector__Kubernetes__SkipTlsVerify: "false"
          probes:
            liveness:
              type: http
              path: /health/ready
              port: 8080
            readiness:
              type: http
              path: /health/ready
              port: 8080
            startup:
              type: http
              path: /health/ready
              port: 8080
service:
  main:
    enabled: false
