image:
  repository: fyb3roptik/threadfin
  tag: 1.2.38@sha256:1a4d7761c21bbff04104348f559c5a8f5aa576d79acc3b6b70afac1653767461
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 34400
persistence:
  config:
    enabled: true
    mountPath: "/home/threadfin/conf"
  temp:
    enabled: true
    mountPath: "/tmp/threadfin"
    type: emptyDir
