image:
  pullPolicy: IfNotPresent
  repository: docker.io/phasecorex/red-discordbot
  tag: full@sha256:af268ce05271b7421235d06139598bb855c31fa93e594044b36ad873b3ed3ad4
persistence:
  data:
    enabled: true
    mountPath: /data

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PREFIX: ""
            TOKEN: ""
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
