image:
  pullPolicy: IfNotPresent
  repository: seaduboi/broadcast-box
  tag: latest@sha256:559f28d650d8a75ae17222c02a59a1a1e2c6f5827709bc64b267b31ad5260d4c
service:
  main:
    ports:
      main:
        port: 8080
        protocol: http
        targetPort: 8080
      webrtc:
        enabled: true
        port: 60006
        protocol: udp
        targetPort: 60006
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NETWORK_TEST_ON_START: false
            INCLUDE_PUBLIC_IP_IN_NAT_1_TO_1_IP: true
            UDP_MUX_PORT: "{{ .Values.service.main.ports.webrtc.port }}"
