image:
  repository: docker.io/bitnamisecure/memcached
  pullPolicy: IfNotPresent
  tag: latest@sha256:5129395cd5101713cbcb4fbfdf6dc94b9798e0cad5a55c3d4b4339db3e8675b9

service:
  main:
    ports:
      main:
        port: 11211
        protocol: tcp
        targetPort: 11211
configmap:
  dashboard:
    enabled: true
    labels:
      grafana_dashboard: "1"
    data:
      memcached.json: >-
        {{ .Files.Get "dashboard.json" | indent 8 }}
