image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/booklore-app/booklore
  tag: v1.9.0@sha256:09f95e1ac54d05f1e9bf6235c3e9341c4061349afa129b5823fe49522a224fd5
service:
  main:
    ports:
      main:
        protocol: http
        port: 6060
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATABASE_URL:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: jdbc-mariadb
            DATABASE_USERNAME: "{{ .Values.mariadb.mariadbUsername }}"
            DATABASE_PASSWORD: "{{ .Values.mariadb.password }}"
            BOOKLORE_PORT: "{{ .Values.service.main.ports.main.port }}"
persistence:
  data:
    enabled: true
    mountPath: /app/data
  varrun:
    enabled: false
mariadb:
  enabled: true
  mariadbUsername: booklore
