image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/sameersbn/apt-cacher-ng
  tag: latest@sha256:82f55f9c8f627cee8ef5f710c1745388d79d3a3f2f3150353e6500021bec11b4
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3142
        protocol: tcp
        targetPort: 3142
persistence:
  apt-cacher-ng:
    enabled: true
    mountPath: /var/cache/apt-cacher-ng
