image:
  repository: quay.io/jupyter/base-notebook
  pullPolicy: IfNotPresent
  tag: 2025-09-19@sha256:aa44ee66c9ec45906784a8b5795544466202b8d3d4ae3ec80e506af34239499c
minimalImage:
  repository: quay.io/jupyter/minimal-notebook
  pullPolicy: IfNotPresent
  tag: 2025-09-19@sha256:c43ffbdf31fbf28a7e9d5bfac94c8dc4afb9dbe82bc0f238cd8e67c85d25332a
rImage:
  repository: quay.io/jupyter/r-notebook
  pullPolicy: IfNotPresent
  tag: 2025-09-19@sha256:c9a7ea73375081a96ce7a23f2a6ea28706602fe15c64318b8d0520b5ee842386
scipyImage:
  repository: quay.io/jupyter/scipy-notebook
  pullPolicy: IfNotPresent
  tag: 2025-09-19@sha256:7dc9b4f102d75a49a7029edb4320658e9105cfe5bf782a68dc40794cb2c648ff
tensorflowImage:
  repository: quay.io/jupyter/tensorflow-notebook
  pullPolicy: IfNotPresent
  tag: 2025-09-19@sha256:c21833af2918202964361d837d5745174127416f5366c3fc027583dd2184119c
datascienceImage:
  repository: quay.io/jupyter/datascience-notebook
  pullPolicy: IfNotPresent
  tag: 2025-09-19@sha256:55ea0ff010be6b9946a29259bdd79fb47a9dfa7ae03668a8ba5b6a5e11d43147
pysparkImage:
  repository: quay.io/jupyter/pyspark-notebook
  pullPolicy: IfNotPresent
  tag: 2025-09-19@sha256:ae7af7ac9932ea4a3a3a75f8714185976296e57e4341f67bfc4e98a804f6105a
allsparkImage:
  repository: quay.io/jupyter/all-spark-notebook
  pullPolicy: IfNotPresent
  tag: 2025-09-19@sha256:dc58917913b8c6ef9b134c55a76883d375ac008d94ef43742f697eabbf1c0853
jupyter:
  jupyter_cmd: lab
  restartable: true
service:
  main:
    ports:
      main:
        port: 10300
        protocol: http
        targetPort: 8888
persistence:
  data:
    enabled: true
    mountPath: /home/jovyan/work

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            NB_UID: "{{ .Values.securityContext.container.PUID }}"
            NB_GID: "{{ .Values.securityContext.pod.fsGroup }}"
            NB_UMASK: "{{ .Values.securityContext.container.UMASK }}"
            # User Defined
            DOCKER_STACKS_JUPYTER_CMD: "{{ .Values.jupyter.jupyter_cmd }}"
            RESTARTABLE: '{{ ternary "yes" "no" .Values.jupyter.restartable }}'
updated: true
