image:
  repository: quay.io/jupyter/base-notebook
  pullPolicy: IfNotPresent
  tag: 2025-09-19@sha256:ca54c8cf802d288786e182e1ae11a023c810428f4828b92d2af03a6e80ec1f5e
minimalImage:
  repository: quay.io/jupyter/minimal-notebook
  pullPolicy: IfNotPresent
  tag: 2025-09-19@sha256:d0521e708ebf16ba4377d38d271c12e94e760dde2dbee9f46cbe7db913e19f07
rImage:
  repository: quay.io/jupyter/r-notebook
  pullPolicy: IfNotPresent
  tag: 2025-09-19@sha256:a72bdbc4c9f0e8b28294ccfb42039ddec6a3c61caf65c035b70b91ac640c1359
scipyImage:
  repository: quay.io/jupyter/scipy-notebook
  pullPolicy: IfNotPresent
  tag: 2025-09-19@sha256:6f8e1d5789393033fae501a01eb57f03475daeab3238bf6ec3002171b978495b
tensorflowImage:
  repository: quay.io/jupyter/tensorflow-notebook
  pullPolicy: IfNotPresent
  tag: 2025-09-19@sha256:6294d525b6383bcc985cb0e19bd50d6afcdc958529c6fe1722b1b52765297d41
datascienceImage:
  repository: quay.io/jupyter/datascience-notebook
  pullPolicy: IfNotPresent
  tag: 2025-09-19@sha256:955f5166f93a206c52690e9f7192fe2f53d774b3cb5b99acbd77d9347a7f3add
pysparkImage:
  repository: quay.io/jupyter/pyspark-notebook
  pullPolicy: IfNotPresent
  tag: 2025-09-19@sha256:9bad6312826034202c99c96b76fe0c6554d99fd39261f7a005748a3a424228a4
allsparkImage:
  repository: quay.io/jupyter/all-spark-notebook
  pullPolicy: IfNotPresent
  tag: 2025-09-19@sha256:2aea18f6866ead8bc80396606260d844f30ed9484d3e3117bd7f7191f55750ed
jupyter:
  jupyter_cmd: lab
  restartable: true
service:
  main:
    ports:
      main:
        port: 10300
        protocol: http
        targetPort: 8888
persistence:
  data:
    enabled: true
    mountPath: /home/jovyan/work

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            NB_UID: "{{ .Values.securityContext.container.PUID }}"
            NB_GID: "{{ .Values.securityContext.pod.fsGroup }}"
            NB_UMASK: "{{ .Values.securityContext.container.UMASK }}"
            # User Defined
            DOCKER_STACKS_JUPYTER_CMD: "{{ .Values.jupyter.jupyter_cmd }}"
            RESTARTABLE: '{{ ternary "yes" "no" .Values.jupyter.restartable }}'
updated: true
