words:
  - alfi
  - APPNAME
  - archivebox
  - astro
  - astrojs
  - automount
  - Bitnami
  - bitpushr
  - cloudnative
  - clusterissuer
  - Clustertool
  - CNPG
  - codespace
  - Codespaces
  - Collabora
  - configmap
  - crossorigin
  - Dockerhub
  - downscaling
  - Dragonfish
  - fluxcd
  - frontmatter
  - gitops
  - heavyscript
  - hyperconverged
  - iscsi
  - Jagr
  - jagrbombs
  - Jailman
  - Jellyfin
  - Kjeld
  - kofeh
  - kqmaverick
  - kubeapps
  - Merch
  - metallb
  - Minio
  - mountpoint
  - Nextcloud
  - Noob
  - notoriosly
  - ornias
  - pagefind
  - Photoprism
  - Pihole
  - playform
  - Postgreqsql
  - preconfigured
  - Prowlarr
  - PVCPATH
  - Radarr
  - Schouten
  - sdimovv
  - shadofall
  - shoutout
  - showstealers
  - Sidero
  - statefulset
  - statefulsets
  - Syncthing
  - tailscale
  - TCCR
  - templating
  - Traefik
  - truecharts
  - upscaling
  - Vaultwarden
  - Xstar
  - Xsystems
